version: '3.8'
services:
  dev-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db_fiverr
      - MYSQL_ROOT_USER=root
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - akiravd
  test-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db_fiverr
      - MYSQL_ROOT_USER=root
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - akiravd
volumes:
  mysql_db:
    driver: local
networks:
  akiravd:
