version: '3.8'
services:
  dev-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db_dev
      - MYSQL_ROOT_USER=root
    volumes:
      - mysql_dev:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - akiravd
  test-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db_test
      - MYSQL_ROOT_USER=root
    volumes:
      - mysql_test:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - akiravd
volumes:
  mysql_dev:
    driver: local
  mysql_test:
    driver: local
networks:
  akiravd:
